userDetails/userDetails/urls.py
from django.contrib import admin
from django.urls import path ,include
from user_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicApp/',include('user_app.urls'))
]

userDetails/user_app/urls.py
from django.urls import path
#from . import views
from user_app import views
#Template naming ..
app_name='userBasicApp'
urlpatterns=[
   path('relative/',views.relative,name='relative'),
   path('other/',views.other,name='other'),
   path('basic/',views.basic,name='basic')
]

userDetails/user_app/models.py
from django.db import models

# Create your models here.

userDetails/user_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    data_dic={'title':"India's Best Examination Site ",'name':'Pragati','date':'2022-06-12'}
    return render(request,'basicApp/index.html',data_dic)
def relative(request):
    return render(request,'basicApp/relative_url_template.html')
def other(request):
    return render(request,'basicApp/other.html')
def basic(request):
    return render(request,'basicApp/basic.html')

userDetails/templates/basicApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 {%block block_title%}
    <title>Basic Title</title>
  {%endblock%}
  </head>
  <body>

<nav class="navbar navbar-default navbar-static-top">
   <div class="container">
    <ul class="nav navbar-nav">
      <li ><a class="navbar-brand" href="{%url 'index'%}">BRAND</a> </li>
      <li ><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a> </li>
      <li ><a class="navbar-link" href="{%url 'userBasicApp:other'%}">Other</a> </li>
    </ul>

   </div>

</nav>
<div class="container">
  {% block body_block%}
  {% endblock %}

</div>
  </body>
</html>

userDetails/templates/basicApp/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <h1>Welcome to basic html</h1>
    <a href="{% url 'userBasicApp:relative'%}" class='btn btn-primary'>Relative Template Page</a>
    ||<a href="{% url 'userBasicApp:other'%}" class='btn btn-primary'>otherTemplate Page</a>
    ||<a href="{% url 'userBasicApp:basic'%}" class='btn btn-primary'>Basic Template Page</a>


  </body>
</html>

userDetails/templates/basicApp/index.html
<!DOCTYPE html>
{%extends "basicApp/base.html"%}
 {%block block_title%}
        <title>{{title|cut:'Best'}}</title>
 {%endblock%}
  {%block body_block%}
   <h1>Welcome to Index Page</h1>
   <h1>This is an example of template inheritance!</h1>
   {%endblock%}

userDetails/templates/basicApp/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
<h1>Welcome to Other</h1>
<a href="{% url 'userBasicApp:relative'%}" class='btn btn-primary'>Relative Template Page</a>
||<a href="{% url 'userBasicApp:other'%}" class='btn btn-primary'>otherTemplate Page</a>
||<a href="{% url 'userBasicApp:basic'%}" class='btn btn-primary'>Basic Template Page</a>

  </body>
</html>

userDetails/templates/basicApp/relative_url_template.html
<!DOCTYPE html>
{%extends 'basicApp/base.html'%}
{%block block_title%}
   <title>Relative Block</title>
{%endblock%}
{%block body_block%}

<a href="{% url 'userBasicApp:relative'%}" class='btn btn-primary'>Relative Template Page</a>
||<a href="{% url 'userBasicApp:other'%}" class='btn btn-primary'>otherTemplate Page</a>
||<a href="{% url 'userBasicApp:basic'%}" class='btn btn-primary'>Basic Template Page</a>
{%endblock%}